import Head from 'next/head'
import Menu from 'components/menu'
import Conteudo from 'components/conteudo'

export default function Home() {
  return (
    <div className="bg- bg-white">
      <Head>
        <title>mais conasems</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Conteudo />
    </div>
  )
}
